/* Generated By:JJTree: Do not edit this line. ASTDoWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDoWhileStatement extends SimpleNode {
  public ASTDoWhileStatement(int id) {
    super(id);
  }

  public ASTDoWhileStatement(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c211147e6b564eb3d46a220434d07f4 (do not edit this line) */
