/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction extends SimpleNode {
	public ASTFunction(int id) {
		super(id);
	}

	public ASTFunction(PatternParser p, int id) {
		super(p, id);
	}
	@Override
	public String generateJava() {
		String s = "\t" + value.toString().replace("@", "_at_") + "(";
		for(int i = 0; i < jjtGetNumChildren(); i++){
			// 1 Filho
			if (jjtGetNumChildren() == 0) {
				SimpleNode args = (SimpleNode) jjtGetChild(0);
				return s + args.generateJava() + ");\n";
			}
			//Varios Filhos
			SimpleNode args = (SimpleNode) jjtGetChild(i);
			
			//Ultimo filho
			if (i == jjtGetNumChildren()-1) {
				s += args.generateJava();
				break;
			}
			s += args.generateJava() + ", ";
		}

		return s + ");\n";
	}

}
/* JavaCC - OriginalChecksum=b96d639a0d4bfd19398c15ac26aff3e5 (do not edit this line) */
