/* Generated By:JJTree: Do not edit this line. ASTIf_Statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIf_Statement extends SimpleNode {
  public ASTIf_Statement(int id) {
    super(id);
  }

  public ASTIf_Statement(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce6b5b308518603a0d8b4d4075afc86c (do not edit this line) */
