/* Generated By:JJTree: Do not edit this line. ASTOperator_Binary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperator_Binary extends SimpleNode {
  public ASTOperator_Binary(int id) {
    super(id);
  }

  public ASTOperator_Binary(PatternParser p, int id) {
    super(p, id);
  }
  
  @Override
 	public String generateJava() {
 		return this.value.toString();
 	}
}
/* JavaCC - OriginalChecksum=666d3dce41740b982e8310a4c6104a6a (do not edit this line) */
