/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(PatternParser p, int id) {
    super(p, id);
  }

  
  @Override
	public String generateJava() {
	  String s = "public class Pattern {\n";
	  for(int i = 0; i < jjtGetNumChildren(); i++){
		  SimpleNode n = (SimpleNode) jjtGetChild(i);
		  s += n.generateJava();
	  }
	  s += "}\n";
	  return s;
	}

}
/* JavaCC - OriginalChecksum=cb35e8a4891bbdc61b702a5258e7a31d (do not edit this line) */