/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTValue extends SimpleNode {
  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=62debff9cfcae21a128dd8f625067a80 (do not edit this line) */
