/* Generated By:JJTree: Do not edit this line. ASTWhile_Statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile_Statement extends SimpleNode {
  public ASTWhile_Statement(int id) {
    super(id);
  }

  public ASTWhile_Statement(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4853c70d8c7bc5300c580d33a720e614 (do not edit this line) */
