/* Generated By:JavaCC: Do not edit this line. PatternParserTreeConstants.java Version 5.0 */
public interface PatternParserTreeConstants
{
  public int JJTIF_EXPRESSION = 0;


  public String[] jjtNodeName = {
    "IF_Expression",
  };
}
/* JavaCC - OriginalChecksum=39dfc9c09b33afe1d995f65d469efdf6 (do not edit this line) */
