/* Generated By:JJTree&JavaCC: Do not edit this line. PatternParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PatternParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int PATTERN = 6;
  /** RegularExpression Id. */
  int PARENTHESIS_OPEN = 7;
  /** RegularExpression Id. */
  int PARENTHESIS_CLOSE = 8;
  /** RegularExpression Id. */
  int BRACKETS_OPEN = 9;
  /** RegularExpression Id. */
  int BRACKETS_CLOSE = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int EQUALS = 12;
  /** RegularExpression Id. */
  int NOT_EQUALS = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;
  /** RegularExpression Id. */
  int VARIABLE = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"Pattern\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"else\"",
    "\"==\"",
    "\"|=\"",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<VARIABLE>",
  };

}
