/* Generated By:JavaCC: Do not edit this line. PatternParserTreeConstants.java Version 5.0 */
public interface PatternParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPATTERN = 1;
  public int JJTVARIABLE = 2;


  public String[] jjtNodeName = {
    "Start",
    "Pattern",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=65fcaf519eb7de2ed3eed82427364a82 (do not edit this line) */
