/* Generated By:JJTree&JavaCC: Do not edit this line. PatternParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PatternParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int PATTERN = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int PARENTHESIS_OPEN = 8;
  /** RegularExpression Id. */
  int PARENTHESIS_CLOSE = 9;
  /** RegularExpression Id. */
  int BRACKETS_OPEN = 10;
  /** RegularExpression Id. */
  int BRACKETS_CLOSE = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int SEMI_COLON = 13;
  /** RegularExpression Id. */
  int NEGATION = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int NOT_EQUALS = 17;
  /** RegularExpression Id. */
  int PLUS_EQUAL = 18;
  /** RegularExpression Id. */
  int MINUS_EQUAL = 19;
  /** RegularExpression Id. */
  int DIV_EQUAL = 20;
  /** RegularExpression Id. */
  int MULT_EQUAL = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int INCREMENT = 24;
  /** RegularExpression Id. */
  int DECREMENT = 25;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 26;
  /** RegularExpression Id. */
  int GREATER = 27;
  /** RegularExpression Id. */
  int LESSER_EQUAL = 28;
  /** RegularExpression Id. */
  int LESSER = 29;
  /** RegularExpression Id. */
  int REMAINDER = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int INTEGER = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int VARIABLE = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"Pattern\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"else\"",
    "\";\"",
    "\"!\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"+=\"",
    "\"-=\"",
    "\"/=\"",
    "\"*=\"",
    "\"+\"",
    "\"-\"",
    "\"++\"",
    "\"--\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
    "\"%\"",
    "\",\"",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<VARIABLE>",
  };

}
