package ParsingTools;
/* Generated By:JJTree: Do not edit this line. ASTBinaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBinaryExpression extends SimpleNode {
	public ASTBinaryExpression(int id) {
		super(id);
	}

	public ASTBinaryExpression(PatternParser p, int id) {
		super(p, id);
	}

	@Override
	public String generateJava() {
		SimpleNode left = (SimpleNode) jjtGetChild(0);
		SimpleNode op = (SimpleNode) jjtGetChild(1);
		SimpleNode right = (SimpleNode) jjtGetChild(2);
		return left.generateJava() + " " + op.generateJava() + " " + right.generateJava();
	}
	/* JavaCC - OriginalChecksum=db40cf98cbb5ad6a19da0b28cdb1489b (do not edit this line) */
}