package ParsingTools;
/* Generated By:JJTree: Do not edit this line. ASTOperand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperand extends SimpleNode {
  public ASTOperand(int id) {
    super(id);
  }

  public ASTOperand(PatternParser p, int id) {
    super(p, id);
  }
  @Override
	public String generateJava() {
	  return value.toString().replace("@","_at_");
	}
}
/* JavaCC - OriginalChecksum=13ac268ce6b682e543ca115e6be65ab8 (do not edit this line) */
