package ParsingTools;
/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryExpression extends SimpleNode {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(PatternParser p, int id) {
    super(p, id);
  }
  
	@Override
	public String generateJava() {
		SimpleNode left = (SimpleNode) jjtGetChild(0);
		SimpleNode right = (SimpleNode) jjtGetChild(1);
		return left.generateJava() + right.generateJava();
	}
}
/* JavaCC - OriginalChecksum=1d9d3c76fa2c66a455cf349dfe945de4 (do not edit this line) */
