package ParsingTools;
/* Generated By:JavaCC: Do not edit this line. PatternParserTreeConstants.java Version 5.0 */
public interface PatternParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFUNCTION = 1;
  public int JJTPATTERN = 2;
  public int JJTUNARYASSIGNMENTSPECIAL = 3;
  public int JJTASSIGNMENT = 4;
  public int JJTDOWHILESTATEMENT = 5;
  public int JJTVOID = 6;
  public int JJTIFSTATEMENT = 7;
  public int JJTWHILESTATEMENT = 8;
  public int JJTUNARYEXPRESSION = 9;
  public int JJTBINARYEXPRESSION = 10;
  public int JJTBLOCK = 11;
  public int JJTOPERAND = 12;
  public int JJTOPERATOR = 13;
  public int JJTOPERATOR_UNARY = 14;
  public int JJTOPERATOR_BINARY = 15;
  public int JJTOPERATOR_ASSIGNMENT = 16;


  public String[] jjtNodeName = {
    "Start",
    "Function",
    "Pattern",
    "UnaryAssignmentSpecial",
    "Assignment",
    "DoWhileStatement",
    "void",
    "IfStatement",
    "WhileStatement",
    "UnaryExpression",
    "BinaryExpression",
    "Block",
    "Operand",
    "Operator",
    "Operator_Unary",
    "Operator_Binary",
    "Operator_Assignment",
  };
}
/* JavaCC - OriginalChecksum=08d2945b755a94d0a275396897dfc216 (do not edit this line) */
