package ParsingTools;
/* Generated By:JJTree&JavaCC: Do not edit this line. PatternParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PatternParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int DO = 6;
  /** RegularExpression Id. */
  int PATTERN = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int PARENTHESIS_OPEN = 9;
  /** RegularExpression Id. */
  int PARENTHESIS_CLOSE = 10;
  /** RegularExpression Id. */
  int BRACKETS_OPEN = 11;
  /** RegularExpression Id. */
  int BRACKETS_CLOSE = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int SEMI_COLON = 14;
  /** RegularExpression Id. */
  int NEGATION = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int NOT_EQUALS = 18;
  /** RegularExpression Id. */
  int PLUS_EQUAL = 19;
  /** RegularExpression Id. */
  int MINUS_EQUAL = 20;
  /** RegularExpression Id. */
  int DIV_EQUAL = 21;
  /** RegularExpression Id. */
  int MULT_EQUAL = 22;
  /** RegularExpression Id. */
  int LESSER_EQUAL = 23;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 24;
  /** RegularExpression Id. */
  int REMAINDER_EQUAL = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int INCREMENT = 28;
  /** RegularExpression Id. */
  int DECREMENT = 29;
  /** RegularExpression Id. */
  int GREATER = 30;
  /** RegularExpression Id. */
  int LESSER = 31;
  /** RegularExpression Id. */
  int REMAINDER = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int INTEGER = 34;
  /** RegularExpression Id. */
  int IDENTIFIER = 35;
  /** RegularExpression Id. */
  int VARIABLE = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"do\"",
    "\"Pattern\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"else\"",
    "\";\"",
    "\"!\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"+=\"",
    "\"-=\"",
    "\"/=\"",
    "\"*=\"",
    "\"<=\"",
    "\">=\"",
    "\"%=\"",
    "\"+\"",
    "\"-\"",
    "\"++\"",
    "\"--\"",
    "\">\"",
    "\"<\"",
    "\"%\"",
    "\",\"",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<VARIABLE>",
  };

}
