/* Generated By:JJTree: Do not edit this line. ASTOperator_Assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperator_Assignment extends SimpleNode {
  public ASTOperator_Assignment(int id) {
    super(id);
  }

  public ASTOperator_Assignment(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75c830cf686f8f4252c758e6a36c0ecb (do not edit this line) */
