/* Generated By:JJTree: Do not edit this line. ASTOperand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperand extends SimpleNode {
  public ASTOperand(int id) {
    super(id);
  }

  public ASTOperand(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a13e686de535e47360e74318039c043 (do not edit this line) */
