
/* Generated By:JJTree: Do not edit this line. ASTUnaryAssignmentSpecial.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryAssignmentSpecial extends SimpleNode {
  public ASTUnaryAssignmentSpecial(int id) {
    super(id);
  }

  public ASTUnaryAssignmentSpecial(PatternParser p, int id) {
    super(p, id);
  }
  
  public String generateJava() {
	  	SimpleNode unary = (SimpleNode) jjtGetChild(0);										
		return "\t" + unary.generateJava() + ";\n"; 	
	}
}
/* JavaCC - OriginalChecksum=c9b69129bdbcb90bde6795d4e600b05c (do not edit this line) */
